serviceMaps:
  serviceName: application
  mappings:
    - version: 1.0
      description: Persists application details in tables
      fromTopic: save-application
      isTransaction: true
      isAuditEnabled: true
      module: APPLICATION
      objecIdJsonPath: $.id
      tenantIdJsonPath: $.tenantId
      transactionCodeJsonPath: $.filingNumber
      auditAttributeBasePath: application
      queryMaps:

        - query: INSERT INTO dristi_application(id, tenant_id, case_id, filing_number, cnr_number, reference_id, created_date, application_created_by, on_behalf_of, application_type, application_number, wf_status, comments, is_active, additional_details, created_by, last_modified_by, created_time, last_modified_time) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?,?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
          basePath: application
          jsonMaps:
            - jsonPath: $.application.id
            - jsonPath: $.application.tenantId
            - jsonPath: $.application.caseId
            - jsonPath: $.application.filingNumber
            - jsonPath: $.application.cnrNumber
            - jsonPath: $.application.referenceId
            - jsonPath: $.application.createdDate
            - jsonPath: $.application.createdBy
            - jsonPath: $.application.onBehalfOf
            - jsonPath: $.application.applicationType
            - jsonPath: $.application.applicationNumber
            - jsonPath: $.application.status
            - jsonPath: $.application.comment
              type: JSON
              dbType: JSONB
            - jsonPath: $.application.isActive
            - jsonPath: $.application.additionalDetails
              type: JSON
              dbType: JSONB
            - jsonPath: $.application.auditDetails.createdBy
            - jsonPath: $.application.auditDetails.lastModifiedBy
            - jsonPath: $.application.auditDetails.createdTime
            - jsonPath: $.application.auditDetails.lastModifiedTime

        - query: INSERT INTO dristi_application_document(id, filestore_id, document_uid, document_type, application_id, additional_details, created_by, last_modified_by, created_time, last_modified_time) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
          basePath: application.documents.*
          jsonMaps:
            - jsonPath: $.application.documents.*.id
            - jsonPath: $.application.documents.*.fileStore
            - jsonPath: $.application.documents.*.documentUid
            - jsonPath: $.application.documents.*.documentType
            - jsonPath: $.application.id
            - jsonPath: $.application.documents.*.additionalDetails
              type: JSON
              dbType: JSONB
            - jsonPath: $.application.documents.*.auditDetails.createdBy
            - jsonPath: $.application.documents.*.auditDetails.lastModifiedBy
            - jsonPath: $.application.documents.*.auditDetails.createdTime
            - jsonPath: $.application.documents.*.auditDetails.lastModifiedTime

        - query: INSERT INTO dristi_statutes_and_sections(id, tenant_id, statute_id, section_id, application_id, additional_details, created_by, last_modified_by, created_time, last_modified_time) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?) ON CONFLICT (id) DO UPDATE SET statute_id = EXCLUDED.statute_id, section_id = EXCLUDED.section_id, application_id = EXCLUDED.application_id, additional_details = EXCLUDED.additional_details, last_modified_by = EXCLUDED.last_modified_by, last_modified_time = EXCLUDED.last_modified_time, created_time = EXCLUDED.created_time, created_by = EXCLUDED.created_by;
          basePath: application.statuteSection
          jsonMaps:
            - jsonPath: $.application.statuteSection.id
            - jsonPath: $.application.statuteSection.tenantId
            - jsonPath: $.application.statuteSection.statute
            - jsonPath: $.application.statuteSection.sections.*
            - jsonPath: $.application.id
            - jsonPath: $.application.statuteSection.additionalDetails
              type: JSON
              dbType: JSONB
            - jsonPath: $.application.statuteSection.auditDetails.createdBy
            - jsonPath: $.application.statuteSection.auditDetails.lastModifiedBy
            - jsonPath: $.application.statuteSection.auditDetails.createdTime
            - jsonPath: $.application.statuteSection.auditDetails.lastModifiedTime

        - query: INSERT INTO dristi_application_issued_by(id, tenant_id, statute_id, section_id, application_id, additional_details, created_by, last_modified_by, created_time, last_modified_time) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?) ON CONFLICT (id) DO UPDATE SET statute_id = EXCLUDED.statute_id, section_id = EXCLUDED.section_id, application_id = EXCLUDED.application_id, additional_details = EXCLUDED.additional_details, last_modified_by = EXCLUDED.last_modified_by, last_modified_time = EXCLUDED.last_modified_time, created_time = EXCLUDED.created_time, created_by = EXCLUDED.created_by;
          basePath: application.issuedBy
          jsonMaps:
            - jsonPath: $.application.issuedBy.id
            - jsonPath: $.application.issuedBy.tenantId
            - jsonPath: $.application.issuedBy.judgeId.*
            - jsonPath: $.application.issuedBy.benchId
            - jsonPath: $.application.issuedBy.courtId
            - jsonPath: $.application.id
            - jsonPath: $.application.issuedBy.auditDetails.createdBy
            - jsonPath: $.application.issuedBy.auditDetails.lastModifiedBy
            - jsonPath: $.application.issuedBy.auditDetails.createdTime
            - jsonPath: $.application.issuedBy.auditDetails.lastModifiedTime

    - version: 1.0
      description: Update application details in tables
      fromTopic: update-application
      isTransaction: true
      isAuditEnabled: true
      module: APPLICATION
      objecIdJsonPath: $.id
      tenantIdJsonPath: $.tenantId
      transactionCodeJsonPath: $.filingNumber
      auditAttributeBasePath: application
      queryMaps:
        - query: UPDATE dristi_application SET caseId=?,filingNumber=?,cnrNumber=?,referenceId=?,createdDate=?,applicationCreatedBy=?,onBehalfOf=?,applicationType=?,applicationNumber=?,statuteSection=?,issuedBy=?,status=?,comment=?,isActive=?,additionalDetails=?,lastModifiedBy=?,lastModifiedTime=? WHERE id=? ;
          basePath: application
          jsonMaps:
            - jsonPath: $.application.caseId
            - jsonPath: $.application.filingNumber
            - jsonPath: $.application.cnrNumber
            - jsonPath: $.application.referenceId
            - jsonPath: $.application.createdDate
            - jsonPath: $.application.createdBy
            - jsonPath: $.application.onBehalfOf
              type: JSON
              dbType: JSONB
            - jsonPath: $.application.applicationType
            - jsonPath: $.application.applicationNumber
            - jsonPath: $.application.statuteSection
              type: JSON
              dbType: JSONB
            - jsonPath: $.application.issuedBy
              type: JSON
              dbType: JSONB
            - jsonPath: $.application.status
            - jsonPath: $.application.comment
              type: JSON
              dbType: JSONB
            - jsonPath: $.application.isActive
            - jsonPath: $.application.additionalDetails
              type: JSON
              dbType: JSONB
            - jsonPath: $.application.auditDetails.lastModifiedBy
            - jsonPath: $.application.auditDetails.lastModifiedTime
            - jsonPath: $.application.id

        - query: INSERT INTO dristi_application_document(id, fileStore, documentUid, documentType, application_id, additionalDetails) VALUES (?, ?, ?, ?, ?, ?) ON CONFLICT (id) DO UPDATE SET fileStore = EXCLUDED.fileStore, documentUid = EXCLUDED.documentUid, documentType = EXCLUDED.documentType, application_id = EXCLUDED.application_id, additionalDetails = EXCLUDED.additionalDetails;
          basePath: application.documents.*
          jsonMaps:
            - jsonPath: $.application.documents.*.id
            - jsonPath: $.application.documents.*.fileStore
            - jsonPath: $.application.documents.*.documentUid
            - jsonPath: $.application.documents.*.documentType
            - jsonPath: $.application.id
            - jsonPath: $.application.documents.*.additionalDetails
              type: JSON
              dbType: JSONB

    - version: 1.0
      description: Update application status in tables
      fromTopic: update-application-status-application
      isTransaction: true
      isAuditEnabled: true
      module: APPLICATION
      objectIdJsonPath: $.id
      tenantIdJsonPath: $.tenantId
      transactionCodeJsonPath: $.applicationNumber
      auditAttributeBasePath: $
      queryMaps:
        - query: UPDATE dristi_application SET status = ?, lastmodifiedby = ?,  lastmodifiedtime = ? WHERE applicationNumber=?;
          basePath: $
          jsonMaps:
            - jsonPath: $.status
            - jsonPath: $.auditDetails.lastModifiedBy
            - jsonPath: $.auditDetails.lastModifiedTime
            - jsonPath: $.applicationNumber

    - version: 1.0
      description: Update application comments in tables
      fromTopic: update-application-comments-application
      isTransaction: true
      isAuditEnabled: true
      module: APPLICATION
      objectIdJsonPath: $.id
      tenantIdJsonPath: $.tenantId
      transactionCodeJsonPath: $.applicationNumber
      auditAttributeBasePath: $
      queryMaps:
        - query: UPDATE dristi_application SET comment = ?, lastmodifiedby = ?,  lastmodifiedtime = ? WHERE applicationNumber=?;
          basePath: $
          jsonMaps:
            - jsonPath: $.comment
              type: JSON
              dbType: JSONB
            - jsonPath: $.auditDetails.lastModifiedBy
            - jsonPath: $.auditDetails.lastModifiedTime
            - jsonPath: $.applicationNumber