export const HearingWorkflowAction = {
  SETDATE: "SET_DATE",
  ABANDON: "ABANDON",
  RESCHEDULE: "RESCHEDULE",
  BULK_RESCHEDULE: "BULK_RESCHEDULE",
};

export const HearingWorkflowState = {
  OPTOUT: "OPT_OUT",
  INPROGRESS: "IN_PROGRESS",
  COMPLETED: "COMPLETED",
  ABATED: "ABATED",
  SCHEDULED: "SCHEDULED",
};
