export const paymentType = {
  TASK_SUMMON: "task-summons",
  TASK_NOTICE: "task-notice",
  TASK_SUMMON_ADVANCE_CARRYFORWARD: "TASK_SUMMON_ADVANCE_CARRYFORWARD",
  TASK_NOTICE_ADVANCE_CARRYFORWARD: "TASK_NOTICE_ADVANCE_CARRYFORWARD",
  ORDER_MANAGELIFECYCLE: "order-default",
  SUMMON_WARRANT_STATUS: "SUMMON_WARRANT_STATUS",
  NOTICE_STATUS: "NOTICE_STATUS",
  ASYNC_ORDER_SUBMISSION_MANAGELIFECYCLE: "application-order-submission-default",
  PAYMENT_PENDING_POST: "PAYMENT_PENDING_POST",
  PAYMENT_PENDING_EMAIL: "PAYMENT_PENDING_EMAIL",
  PAYMENT_PENDING_SMS: "PAYMENT_PENDING_SMS",
};
