export const SubmissionWorkflowAction = { CREATE: "CREATE", ESIGN: "ESIGN", REJECT: "REJECT", ABANDON: "ABANDON", APPROVE: "APPROVE" };
export const SubmissionWorkflowState = {
  PENDINGSUBMISSION: "PENDINGSUBMISSION",
  PENDINGPAYMENT: "PENDINGPAYMENT",
  PENDINGESIGN: "PENDINGESIGN",
  PENDINGAPPROVAL: "PENDINGAPPROVAL",
  PENDINGREVIEW: "PENDINGREVIEW",
};
