export const SubmissionWorkflowAction = { CREATE: "CREATE", ESIGN: "ESIGN", REJECT: "REJECT", ABANDON: "ABANDON", APPROVE: "APPROVE", SET_TERM_BAIL: "SEND_BACK" };
export const SubmissionWorkflowState = {
  PENDINGSUBMISSION: "PENDINGSUBMISSION",
  PENDINGPAYMENT: "PENDINGPAYMENT",
  PENDINGESIGN: "PENDINGESIGN",
  PENDINGAPPROVAL: "PENDINGAPPROVAL",
  PENDINGREVIEW: "PENDINGREVIEW",
  PENDINGRESPONSE: "PENDINGRESPONSE",
  COMPLETED: "COMPLETED",
  DELETED: "DELETED",
  ABATED: "ABATED",
  REJECTED: "REJECTED",
};
