CREATE TABLE transaction_details (
    merchant_id VARCHAR(30),
    operating_mode VARCHAR(30),
    merchant_country VARCHAR(30),
    merchant_currency VARCHAR(30),
    posting_amount NUMERIC(12,2),
    other_details VARCHAR(255),
    success_url VARCHAR(255),
    fail_url VARCHAR(255),
    aggregator_id VARCHAR(30),
    merchant_order_number VARCHAR(30) PRIMARY KEY,
    merchant_customer_id VARCHAR(30),
    pay_mode VARCHAR(30),
    access_medium VARCHAR(30),
    transaction_source VARCHAR(30),
    created_by varchar(64) NULL,
    last_modified_by varchar(64) NULL,
    created_time int8 NULL,
    last_modified_time int8 NULL,
    transaction_status varchar(64) NULL,
    sbi_epay_ref_id varchar(64) NULL,
    reason varchar(1000) NULL,
    bank_code varchar(64) NULL,
    bank_reference_number varchar(64) NULL,
    transaction_date varchar(64) NULL,
    cin varchar(64) NULL,
    total_fee_gst NUMERIC(12,2),
    row_number int4 NULL,
    ref1 varchar(64) NULL,
    ref2 varchar(64) NULL,
    ref3 varchar(64) NULL,
    ref4 varchar(64) NULL,
    ref5 varchar(64) NULL,
    ref6 varchar(64) NULL,
    ref7 varchar(64) NULL,
    ref8 varchar(64) NULL,
    ref9 varchar(64) NULL
);
