openapi: 3.0.0
info:
  title: Advocate and advocate clerk registry
  description: |
    This document houses API specifications to register court system users - advocate, advocate clerk etc.. This registry sits on top of the base user/individual registries. All users will be registered in the DIGIT individual/user registries with mobile number, name and other basic fields. This registry only stores extra information as needed for dispute resolution systems. While this is a very basic registry currently, this can evolve into a very detailed registry in future versions. Verification of advocate/clerk credentials is left to the implementation.
  version: 0.1.0
tags:
  - name: Advocate
    description: APIs to register advocates
  - name: AdvocateClerk
    description: APIs to register advocate clerks
paths:
  /advocate/v1/_create:
    post:
      tags:
        - Advocate
      summary: Register a new advocate
      description: |
        API to register and verify an advocate.
      requestBody:
        description: Details for the user registration + RequestInfo meta data.
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/AdvocateRequest'
        required: true
      responses:
        '201':
          description: ResponseInfo with advocate info updated successfully
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/AdvocateResponse'
        '400':
          description: Advocate(s) registration failed. Response body to provide specifics of failure.
          content:
            '*/*':
              schema:
                $ref: >-
                  https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/ErrorRes
  /advocate/v1/_update:
    post:
      tags:
        - Advocate
      summary: Update advocate requests
      requestBody:
        description: Details of the registered advocate + RequestInfo meta data.
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/AdvocateRequest'
        required: true
      responses:
        '201':
          description: ResponseInfo with advocate data updated successfully
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/AdvocateResponse'
        '400':
          description: Advocate update failed. Response body to provide specifics of failure.
          content:
            '*/*':
              schema:
                $ref: >-
                  https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/ErrorRes
  
  /advocate/v1/_search:
    post:
      tags:
        - Advocate
      summary: Search for registered advocates
      requestBody:
        description: Search criteria + RequestInfo meta data.
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/AdvocateSearchRequest'
        required: true
      responses:
        '201':
          description: ResponseInfo with advocates matching search criteria
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/AdvocateResponse'
        '400':
          description: Advocate search failed. Refer to response body for specifics.
          content:
            '*/*':
              schema:
                $ref: >-
                  https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/ErrorRes
  
  /clerk/v1/_create:
    post:
      tags:
        - AdvocateClerk
      summary: Register a new advocate clerk
      description: |
        API to register and verify an advocate clerk
      requestBody:
        description: Details for the user registration + RequestInfo meta data.
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/AdvocateClerkRequest'
        required: true
      responses:
        '201':
          description: ResponseInfo with advocate info updated successfully
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/AdvocateClerkResponse'
        '400':
          description: Advocate clerk registration failed. Response body to provide specifics of failure. 
          content:
            '*/*':
              schema:
                $ref: >-
                  https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/ErrorRes
  
  /clerk/v1/_update:
    post:
      tags:
        - AdvocateClerk
      summary: Update advocate clerk requests
      requestBody:
        description: Details of the registered advocate + RequestInfo meta data.
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/AdvocateClerkRequest'
        required: true
      responses:
        '201':
          description: ResponseInfo with advocate data updated successfully
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/AdvocateClerkResponse'
        '400':
          description: Advocate clerk update failed. Response body to provide specifics of failure.
          content:
            '*/*':
              schema:
                $ref: >-
                  https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/ErrorRes
  
  /clerk/v1/_search:
    post:
      tags:
        - AdvocateClerk
      summary: Search for registered advocate clerk
      requestBody:
        description: Search criteria + RequestInfo meta data.
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/AdvocateClerkSearchRequest'
        required: true
      responses:
        '201':
          description: ResponseInfo with advocate clerks matching search criteria
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/AdvocateClerkResponse'
        '400':
          description: Advocate clerk search failed. Refer to response body for specifics.
          content:
            '*/*':
              schema:
                $ref: >-
                  https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/ErrorRes
      
components:
  schemas:
    Advocate:
      type: object
      required: [tenantId, userId]
      properties:
        id: 
          type: string
          format: uuid
          description: Autogenerated id of the case. It is the primary key.
          minLength: 36
          maxLength: 36
          readOnly: true
        tenantId:
          type: string
          description: The tenant where this case is operational
          minLength: 2
          maxLength: 128
        applicationNumber:
          type: string
          description: Formatted ID to track the advocate's registration application. This will be shown in notifications and UI. 
          minLength: 2
          maxLength: 64
        barRegistrationNumber:
          type: string
          description: Bar registration number of an advocate issued by the bar council. This is to be validated.
          minLength: 2
          maxLength: 64
        advocateType:
          type: string
          description: Type of advocate to be derived from master data
          example: PROSECUTOR, PUBLIC DEFENDER 
          minLength: 2
          maxLength: 64
        advocateType:
          type: string
          description: Type of advocate
        organisationID:
          type: string
          format: uuid
          description: Organisation/legal firm the advocate belongs to, if any. Organisation to be created in the organisation registry and ID linked here. Optional.
        individualId:
          type: string
          description: >-
            The individual ID (Individual registry) of the advocate containing all their
            details. 
        isActive:
          type: boolean
          description: >-
            Field used for soft delete of records. Will be false if this entity
            is not active within the system.
          default: true
        workflow:
          $ref: >-
            https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/Workflow
        documents:
          type: array
          description: >-
            This can be used to store any relevant documents related to the advocate's practice.
          items:
            $ref: >-
              https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/Document
        auditDetails:
          $ref: >-
            https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/AuditDetails
        additionalDetails:
          type: object
          description: >-
            Any extra fields that are not captured as first class fields can be
            stored here as key/value pairs. Implementation specific.
    
    AdvocateSearchCriteria:
      type: object
      properties:
        id:
          type: string
        barRegistrationNumber:
          type: string
        applicationNumber:
          type: string
    
    AdvocateClerk:
      type: object
      required: [tenantId, userId]
      properties:
        id: 
          type: string
          description: Autogenerated UUID of the user used to uniquely reference this record
          format: uuid
          minLength: 36
          maxLength: 36
          readOnly: true
        tenantId:
          type: string
          description: The tenant this user belongs to. Advocate clerks typically are registered at the state level.
          example: kl
          minLength: 2
          maxLength: 128
        applicationNumber:
          type: string
          description: Formatted application number for registration as advocate clerk.
          minLength: 2
          maxLength: 64
        stateRegnNumber:
          type: string
          description: Registration number of the advocate clerk at the state level. 
          minLength: 2
          maxLength: 64
        individualId:
          type: string
          description: >-
            The individual ID (Individual registry) of the advocate clerk containing all their
            details.
        isActive:
          type: boolean
          description: >-
            Field used for soft delete of records. Will be false if this entity
            is not active within the system.
          default: true
        workflow:
          $ref: >-
            https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/Workflow
        documents:
          type: array
          description: >-
            This can be used to store any relevant documents related to the advocate's practice.
          items:
            $ref: >-
              https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/Document
        auditDetails:
          $ref: >-
            https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/AuditDetails
        additionalDetails:
          type: object
          description: >-
            Any extra fields that are not captured as first class fields can be
            stored here as key/value pairs. Implementation specific.
    
    AdvocateClerkSearchCriteria:
      type: object
      properties:
        id:
          type: string
        applicationNumber:
          type: string
        stateRegnNumber:
          type: string
    
    AdvocateSearchRequest:
      type: object
      properties:
        requestInfo:
          $ref: >-
            https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/RequestInfo
        criteria:
          type: array
          items:
            $ref: '#/components/schemas/AdvocateSearchCriteria'
    
    AdvocateClerkSearchRequest:
      type: object
      properties:
        requestInfo:
          $ref: >-
            https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/RequestInfo
        criteria:
          type: array
          items:
            $ref: '#/components/schemas/AdvocateClerkSearchCriteria'
    
    AdvocateRequest:
      type: object
      properties:
        requestInfo:
          $ref: >-
            https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/RequestInfo
        advocates:
          type: array
          items:
            $ref: '#/components/schemas/Advocate'
    AdvocateResponse:
      type: object
      properties:
        responseInfo:
          $ref: >-
            https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/ResponseInfo
        advocates:
          type: array
          items:
            $ref: '#/components/schemas/Advocate'
        pagination:
          $ref: >-
            https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/Pagination
    AdvocateClerkRequest:
      type: object
      properties:
        requestInfo:
          $ref: >-
            https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/RequestInfo
        clerks:
          type: array
          items:
            $ref: '#/components/schemas/AdvocateClerk'
    AdvocateClerkResponse:
      type: object
      properties:
        responseInfo:
          $ref: >-
            https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/ResponseInfo
        clerks:
          type: array
          items:
            $ref: '#/components/schemas/AdvocateClerk'
        pagination:
          $ref: >-
            https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/Pagination