openapi: 3.0.1
info:
  title: Annotation API Documentation
  description: This draft API specification defines the annotation registries.
  version: 1.0.0
tags:
  - name: Annotation
    description: APIs to create, update and search annotations.
paths:
  /annotation/v1/create:
    post:
      tags:
        - Annotation
      summary: Create new document annotation in the registry
      requestBody:
        description: Details for the new annotation + RequestInfo meta data.
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/AnnotationRequest'
        required: true
      responses:
        '201':
          description: RequestInfo with annotation details created successfully
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/AnnotationResponse'
        '400':
          description: Annotation creation failed
          content:
            '*/*':
              schema:
                $ref: https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/ErrorRes
  /annotation/v1/update:
    post:
      tags:
        - Annotation
      summary: Update/edit a annotation
      description: API to update the annotation.
      requestBody:
        description: Details for updating fields in the annotation + RequestInfo meta data.
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/AnnotationRequest'
        required: true
      responses:
        '200':
          description: ResponseInfo with note details updated successfully
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/AnnotationResponse'
        '400':
          description: Annotation updation failed
          content:
            '*/*':
              schema:
                $ref: https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/ErrorRes
  /annotation/v1/search:
    post:
      tags:
        - Annotation
      summary: Search for Annotation
      requestBody:
        description: Search criteria + RequestInfo meta data.
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/AnnotationSearchRequest'
        required: true
      responses:
        '200':
          description: ResponseInfo with annotation matching search criteria
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/AnnotationListResponse'
        '400':
          description: Annotation search failed. Refer to response body for specifics.
          content:
            '*/*':
              schema:
                $ref: https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/ErrorRes
components:
  schemas:
    Annotation:
      description: Annotation registry
      required:
        - docId
        - annotation
        - content
        - createdBy
        - pageNumber
        - positionWidth
        - positionHeight
        - positionX1
        - positionX2
        - positionY1
        - positionY2
      type: object
      properties:
        id:
          type: string
          readOnly: true
        docId:
          type: string
        annotation:
          type: string
        content:
          type: string
        createdBy:
          type: string
          description: This is userId where annotation created by the user.
          minLength: 2
          maxLength: 64
        pageNumber:
          type: integer
          format: int32
        createdDate:
          type: integer
          format: int64
        positionWidth:
          type: number
          format: double
        positionHeight:
          type: number
          format: double
        positionX1:
          type: number
          format: double
        positionX2:
          type: number
          format: double
        positionY1:
          type: number
          format: double
        positionY2:
          type: number
          format: double
        tenantId:
          type: string
          description: This is tenantId where the system is implemented.
          minLength: 2
          maxLength: 64
        workflow:
          $ref: https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/Workflow
        additionalDetails:
          type: object
          description: This field is meant to hold any extra information that we want to store for a note.
        auditDetails:
          $ref: https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/AuditDetails
    AnnotationRequest:
      type: object
      properties:
        RequestInfo:
          $ref: https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/RequestInfo
        annotation:
          $ref: '#/components/schemas/Annotation'
    AnnotationResponse:
      type: object
      properties:
        ResponseInfo:
          $ref: https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/ResponseInfo
        annotation:
          $ref: '#/components/schemas/Annotation'
    AnnotationSearchRequest:
      type: object
      properties:
        RequestInfo:
          $ref: https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/RequestInfo
        criteria:
          $ref: '#/components/schemas/AnnotationCriteria'
        pagination:
          $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/common-contract-update/Common%20Services/common-contract.yaml#/components/schemas/Pagination'
    AnnotationListResponse:
      type: object
      properties:
        ResponseInfo:
          $ref: https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/ResponseInfo
        list:
          type: array
          items:
            $ref: '#/components/schemas/Annotation'
        pagination:
          $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/common-contract-update/Common%20Services/common-contract.yaml#/components/schemas/Pagination'
    AnnotationCriteria:
      type: object
      properties:
        docId:
          type: string
        createdBy:
          type: string
        contents:
          type: array
          items:
            type: string
        annotations:
          type: array
          items:
            type: string
        defaultFields:
          type: boolean
        createdFromDate:
          type: integer
          format: int64
          description: search annotation within created date range. if only createdFromDate is specified, then annotation for this filing date will be retrieved
        createdToDate:
          type: integer
          format: int64
          