openapi: 3.0.0
info:
  title: Case Management Service
  description: |
    This is a draft API specification for a case management service that provides value added services on top of the Case registry. 
    1. The case management service provides APIs to retrieve the summary and history of a case. 
    2. It updates the master status of the case by looking into the status of all the different entities in the case lifecycle. This is done as per the case classification strategy that was agreed upon. 
    3. The service also provides a way to group/ungroup cases
  version: 0.1.0
tags:
  - name: Case Management Service
    description: APIs of the case management service
  - name: Witness
    description: APIs to add witnesses to a case
paths:
  /casemanager/case/v1/_cmpNumber:
    post:
      tags:
        - Case Management Service
      summary: API to get next valid number from case
      description: |
        A case has multiple different types of numbers like filing number, CMP number, CNR number and CC/ST number. Each of these has its own format, its own sequencing and its uniqueness range. All of these numbers are owned by the Case Registry. 

        There is a need for applications raised against a case use the same CMP numbering series that the case uses and hence this API is to get the next valid CMP number. 

        NOTE-- If more entities like order, hearing or if other sequences like that of CNR or CC/ST number need to be shared as well, then, it would be worthwhile to make a separate registry and service for Numbers. 

      requestBody:
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/CaseCMPRequest'
        required: true
      responses:
        '200':
          description: ResponseInfo with cases matching the search criteria. Empty array is returned in case no cases match the search criteria.
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/CaseCMPResponse'
        '400':
          description: Search failed
          content:
            '*/*':
              schema:
                $ref: >-
                  https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/ErrorRes

  /casemanager/case/v1/_history:
    post:
      tags:
        - Case Management Service
      summary: Provides the case file or case history given a case identifier
      description: |
        API to retrieve the full case file or history given a case identifier
      requestBody:
        description: Details for updating all updatable fields in the court case + RequestInfo meta data.
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/CaseRequest'
        required: true
      responses:
        '200':
          description: ResponseInfo with case details updated successfully
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/CaseFileResponse'
        '400':
          description: Error fetching case file
          content:
            '*/*':
              schema:
                $ref: >-
                  https://raw.githubusercontent.com/egovernments/DIGIT-Specs/common-contract-update/Common%20Services/common-contract.yaml#/components/schemas/ErrorResponse

  /casemanager/case/v1/_group:
    post:
      tags:
        - Case Management Service
      summary: Provides the ability to group cases together for operational and/or other purposes.
      description: |
        API to create a logical grouping of cases for operational reasons. Cases will continue to be treated as separate entities and orders/judgements will be issued separately. This grouping is primarily meant for hearings to be scheduled together.
      requestBody:
        description: Details of the court cases to be grouped together + RequestInfo meta data.
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/CaseGroupRequest'
        required: true
      responses:
        '200':
          description: ResponseInfo with case group created successfully
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/CaseGroupResponse'
        '400':
          description: Error grouping cases together.
          content:
            '*/*':
              schema:
                $ref: >-
                  https://raw.githubusercontent.com/egovernments/DIGIT-Specs/common-contract-update/Common%20Services/common-contract.yaml#/components/schemas/ErrorResponse

  /casemanager/case/v1/_ungroup:
    post:
      tags:
        - Case Management Service
      summary: Provides the ability to ungroup one or more cases from a group.
      description: |
        API to remove a case or all cases from the logical grouping.
      requestBody:
        description: Details of the court cases to be ungrouped + ResponseInfo meta data.
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/CaseGroupRequest'
        required: true
      responses:
        '200':
          description: ResponseInfo with case group created successfully
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/CaseGroupResponse'
        '400':
          description: Error grouping cases together.
          content:
            '*/*':
              schema:
                $ref: >-
                  https://raw.githubusercontent.com/egovernments/DIGIT-Specs/common-contract-update/Common%20Services/common-contract.yaml#/components/schemas/ErrorResponse

  /casemanager/case/v1/_buildcasebundle:
    post:
      tags:
        - Case Management Service
      description: API used to create a case bundle for a single case. This is directly called from the font end, when there is a need to create the bundle at a specific time
      requestBody:
        description: Details of the court cases to be ungrouped + ResponseInfo meta data.
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/CaseBundleRequest'
        required: true
      responses:
        '200':
          description: ResponseInfo with case group created successfully
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/CaseBundleResponse'
        '400':
          description: Error grouping cases together.
          content:
            '*/*':
              schema:
                $ref: >-
                  https://raw.githubusercontent.com/egovernments/DIGIT-Specs/common-contract-update/Common%20Services/common-contract.yaml#/components/schemas/ErrorResponse

  /casemanager/case/v1/bulk/_buildcasebundle:
    post:
      tags:
        - Case Management Service
      description: API used to create a case bundle for multiple cases. This is typically called from the daily midnight cron job. It will query the case-bundle-pdf Index and create case bundle PDFs for the same. It will just store the files and log details with regards start time, end time, case bundles created, bundles failed. Since this is called by cron job, it will just return a success (if method got called) or failure, if something happened
      requestBody:
        description: Details of the court cases to be ungrouped + ResponseInfo meta data.
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/CaseBundleBulkRequest'
        required: true
      responses:
        '200':
          description: ResponseInfo with case group created successfully
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/CaseBundleBulkResponse'
        '400':
          description: Error grouping cases together.
          content:
            '*/*':
              schema:
                $ref: >-
                  https://raw.githubusercontent.com/egovernments/DIGIT-Specs/common-contract-update/Common%20Services/common-contract.yaml#/components/schemas/ErrorResponse

components:
  schemas:
    CaseGroup:
      description: Holds a logical grouping of cases
      required: [caseIds]
      properties:
        id:
          type: string
          description: Autogenerated UUID of the case group. It is the primary key used to search for the case groups.
          minLength: 2
          maxLength: 128
          readOnly: true
        caseIds:
          type: array
          description: The UUID of the cases that are to be grouped together logically
          items:
            type: string
          minItems: 1


    CaseCMPRequest:
      type: object
      properties:
        RequestInfo:
          $ref: >-
            https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/RequestInfo
        criteria:
          $ref: '#/components/schemas/CaseCMPRequestCriteria'

    CaseCMPResponse:
      type: object
      properties:
        ResponseInfo:
          $ref: >-
            https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/ResponseInfo
        cmpNumber:
          type: string

    CaseCMPRequestCriteria:
      type: object
      properties:
        tenantId:
          type: string
        caseId:
          type: string

    CaseFile:
      description: Representation of the case file. This is an aggregation of all the entities across the case lifecycle.
      required:
        - case
      type: object
      properties:
        case:
          $ref: './case-api-0.1.0.yaml#/components/schemas/CourtCase'
        hearings:
          type: array
          items:
            $ref: './hearing-api-0.1.0.yaml#/components/schemas/Hearing'
        witnesses:
          type: array
          items:
            $ref: './hearing-api-0.1.0.yaml#/components/schemas/Hearing'
        orders:
          type: array
          items:
            $ref: '#/components/schemas/OrderTasks'
        applications:
          type: array
          items:
            $ref: './application-api-0.1.0.yaml#/components/schemas/Application'
        evidence:
          type: array
          items:
            $ref: './evidence-api-0.1.0.yaml#/components/schemas/Artifact'

    OrderTasks:
      type: object
      properties:
        order:
          $ref: './order-api-0.1.0.yaml#/components/schemas/Order'
        tasks:
          type: array
          items:
            $ref: './task-api-0.1.0.yaml#/components/schemas/Task'

    CaseRequest:
      type: object
      properties:
        requestInfo:
          $ref: >-
            https://raw.githubusercontent.com/egovernments/DIGIT-Specs/common-contract-update/Common%20Services/common-contract.yaml#/components/schemas/RequestInfo
        criteria:
          $ref: '#/components/schemas/CaseRequestCriteria'
        pagination:
          $ref: >-
            https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/Pagination


    CaseRequestCriteria:
      type: object
      properties:
        tenantId:
          type: string
        caseId:
          type: string
          description: The UUID of the case for which the case file is requested.
        filingNumber:
          type: string
          description: The filing number of the case
        caseNumber:
          type: string
          description: The CNR number of the case for which the case file is requested.

    CaseFileResponse:
      type: object
      properties:
        requestInfo:
          $ref: >-
            https://raw.githubusercontent.com/egovernments/DIGIT-Specs/common-contract-update/Common%20Services/common-contract.yaml#/components/schemas/RequestInfo
        caseFiles:
          type: array
          items:
            $ref: '#/components/schemas/CaseFile'
        pagination:
          $ref: >-
            https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/Pagination


    CaseGroupRequest:
      type: object
      properties:
        requestInfo:
          $ref: >-
            https://raw.githubusercontent.com/egovernments/DIGIT-Specs/common-contract-update/Common%20Services/common-contract.yaml#/components/schemas/RequestInfo
        caseGroups:
          type: array
          items:
            $ref: '#/components/schemas/CaseGroup'

    CaseGroupResponse:
      type: object
      properties:
        responseInfo:
          $ref: >-
            https://raw.githubusercontent.com/egovernments/DIGIT-Specs/common-contract-update/Common%20Services/common-contract.yaml#/components/schemas/ResponseInfo
        caseGroups:
          type: array
          items:
            $ref: '#/components/schemas/CaseGroup'

    CaseBundleRequest:
      type: object
      properties:
        requestInfo:
          $ref: https://raw.githubusercontent.com/egovernments/DIGIT-Specs/common-contract-update/Common%20Services/common-contract.yaml#/components/schemas/RequestInfo
        tenantId:
          type: string
        caseId:
          type: string
          format: uuid
          minLength: 36
          maxLength: 36
        indexId:
          type: string
          format: uuid
          minLength: 36
          maxLength: 36

    CaseBundleResponse:
      type: object
      properties:
        responseInfo:
          $ref: https://raw.githubusercontent.com/egovernments/DIGIT-Specs/common-contract-update/Common%20Services/common-contract.yaml#/components/schemas/ResponseInfo
        fileStoreId:
          type: string
          format: uuid
          minLength: 36
          maxLength: 36

    CaseBundleBulkRequest:
      type: object
      properties:
        requestInfo:
          $ref: https://raw.githubusercontent.com/egovernments/DIGIT-Specs/common-contract-update/Common%20Services/common-contract.yaml#/components/schemas/RequestInfo
        tenantId:
          type: string

    CaseBundleBulkResponse:
      type: object
      properties:
        responseInfo:
          $ref: https://raw.githubusercontent.com/egovernments/DIGIT-Specs/common-contract-update/Common%20Services/common-contract.yaml#/components/schemas/ResponseInfo
        status:
          type: boolean