openapi: 3.0.1
info:
  title: Constituent Element API Documentation
  description: This draft API specification defines the Constituent element registries to a note.
  version: 1.0.0
tags:
  - name: Constituent Element
    description: APIs to create, update and search Constituent element.
paths:
  /constituentelement/v1/create:
    post:
      tags:
        - ConstituentElement
      summary: Create new ConstituentElement in the registry
      requestBody:
        description: Details for the new ConstituentElement + RequestInfo meta data.
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/ConstituentElementRequest'
        required: true
      responses:
        '201':
          description: RequestInfo with ConstituentElement details created successfully
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ConstituentElementResponse'
        '400':
          description: ConstituentElement creation failed
          content:
            '*/*':
              schema:
                $ref: https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/ErrorRes
  /constituentelement/v1/update:
    post:
      tags:
        - ConstituentElement
      summary: Update/edit a ConstituentElement
      description: API to update the ConstituentElement. Updates can changed value of Constituent element checked/unchecked to a note.
      requestBody:
        description: Details for updating isChecked fields with checked/unchecked value + RequestInfo meta data.
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/ConstituentElementUpdateRequest'
        required: true
      responses:
        '200':
          description: ResponseInfo with ConstituentElement details updated successfully
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ConstituentElementUpdateResponse'
        '400':
          description: ConstituentElement updation failed
          content:
            '*/*':
              schema:
                $ref: https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/ErrorRes
  /constituentelement/v1/search:
    post:
      tags:
        - ConstituentElement
      summary: Search for ConstituentElement
      requestBody:
        description: Search criteria + RequestInfo meta data.
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/ConstituentElementSearchRequest'
        required: true
      responses:
        '200':
          description: ResponseInfo with ConstituentElement matching search criteria
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ConstituentElementListResponse'
        '400':
          description: ConstituentElement search failed. Refer to response body for specifics.
          content:
            '*/*':
              schema:
                $ref: https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/ErrorRes
components:
  schemas:
    ConstituentElement:
      type: object
      description: Constituent element registry
      required:
        - constituentelementId
        - noteId
        - isChecked
      properties:
        id:
          type: string
          readOnly: true
        constituentelementId:
          type: string
          description: This is id from constituent element master table id.
          minLength: 2
          maxLength: 64
        noteId:
          type: string
          description: This is noteId where the constituent element have checked/unchecked value to a note.
          minLength: 2
          maxLength: 64
        value:
          type: string
          description: This is the string value of constituent element
        isChecked:
          type: boolean
          description: checked/unchecked value for Constituent element to a note 
    ConstituentElementRequest:
      type: object
      properties:
        RequestInfo:
          $ref: https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/RequestInfo
        constituentelement:
          type: array
          items:
            $ref: '#/components/schemas/ConstituentElement'
    ConstituentElementResponse:
      type: object
      properties:
        ResponseInfo:
          $ref: https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/ResponseInfo
        constituentelements:
          type: array
          items:
            $ref: '#/components/schemas/ConstituentElement'
    ConstituentElementUpdateRequest:
      type: object
      properties:
        RequestInfo:
          $ref: https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/RequestInfo
        constituentelement:
          $ref: '#/components/schemas/ConstituentElement'
    ConstituentElementUpdateResponse:
      type: object
      properties:
        ResponseInfo:
          $ref: https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/ResponseInfo
        constituentelement:
          $ref: '#/components/schemas/ConstituentElement'
    ConstituentElementSearchRequest:
      type: object
      properties:
        RequestInfo:
          $ref: https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/RequestInfo
        criteria:
          $ref: '#/components/schemas/ConstituentElementCriteria'
        pagination:
          $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/Pagination'
    ConstituentElementListResponse:
      type: object
      properties:
        ResponseInfo:
          $ref: https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/ResponseInfo
        list:
          type: array
          items:
            $ref: '#/components/schemas/ConstituentElement'
        pagination:
          $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/common-contract-update/Common%20Services/common-contract.yaml#/components/schemas/Pagination'
    ConstituentElementCriteria:
      type: object
      required:
        - noteId
      properties:
        noteId:
          type: string
        defaultFields:
          type: boolean
