openapi: 3.0.0
info:
  title: Evidence
  description: |
   API specs for uploading artifacts/marking as evidence etc..Chain of custody and other details of evidence history are not handled in this version. Artifacts can be uploaded voluntarily or because of an order or hearing. They can be marked as "EVIDENCE" by the judge anytime during the course of a case. This is modeled as workflow.
  version: 0.1.0
tags:
  - name: Evidence
    description: APIs required to upload digital artifacts for evidence consideration
  
paths:
  /v1/_create:
    post:
      tags:
        - Evidence
      summary: Upload artifacts that could potentially be accepted as evidence
      description: |
        API used to create a new artifact that could become evidence in a case
      requestBody:
        description: Details for the artifact + RequestInfo meta data.
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/EvidenceRequest'
        required: true
      responses:
        '200':
          description: ResponseInfo with artifact(s) updated successfully
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/EvidenceResponse'
        '400':
          description: Artifact(s) creation failed
          content:
            '*/*':
              schema:
                $ref: >-
                  https://raw.githubusercontent.com/egovernments/DIGIT-Specs/common-contract-update/Common%20Services/common-contract.yaml#/components/schemas/ErrorResponse
      x-codegen-request-body-name: ArtifactRequest
  /v1/_update:
    post:
      tags:
        - Evidence
      summary: Update evidence request
      requestBody:
        description: Details for the artifact to be updated + RequestInfo meta data.
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/EvidenceRequest'
        required: true
      responses:
        '201':
          description: ResponseInfo with artifact(s) updated successfully
          content:
            '*/*':
              schema:
                $ref: >-
                 #/components/schemas/EvidenceResponse
        '400':
          description: artifact(s) update failed
          content:
            '*/*':
              schema:
                $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/common-contract-update/Common%20Services/common-contract.yaml#/components/schemas/ErrorResponse'
  /v1/_search:
    post:
      tags:
        - Evidence
      summary: Search for artifacts
      description: |
        API used to search  artifacts using search criteria
      requestBody:
        description: Search criteria for artifact + RequestInfo meta data.
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/EvidenceSearchRequest'
        required: true
      responses:
        '200':
          description: ResponseInfo with artifacts matching search criteria
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/EvidenceSearchResponse'
        '400':
          description: Artifacts search failed. Refer to the response body for specifics.
          content:
            '*/*':
              schema:
                $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/common-contract-update/Common%20Services/common-contract.yaml#/components/schemas/ErrorResponse'
  /v1/addcomment:
    post:
      tags:
        - Evidence
      summary: Add comment in artifacts
      description: |
        API used to add comment in artifacts
      requestBody:
        description: Comments to be added + RequestInfo meta data.
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/EvidenceAddCommentRequest'
        required: true
      responses:
        '200':
          description: ResponseInfo with comment
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/EvidenceAddCommentResponse'
        '400':
          description: Add comment failed. Refer to the response body for specifics.
          content:
            '*/*':
              schema:
                $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/common-contract-update/Common%20Services/common-contract.yaml#/components/schemas/ErrorResponse'
      x-codegen-request-body-name: ArtifactRequest
components:
  schemas:
    Artifact:
      required: [tenantId, caseId, filingNumber]
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: This id is autogenerated id of the artifact. It is the primary key
          readOnly: true
          minLength: 36
          maxLength: 36
        tenantId:
          type: string
          description: This is tenantId of the case based on the state.
        artifactNumber:
          type: string
          description: Identification number assigned when an artifact is uploaded
          minLength: 2
          maxLength: 64
        evidenceNumber:
          type: string
          description: Formatted evidence number assigned after evidence is accepted by the deciding authority.
          minLength: 2
          maxLength: 64
        externalRefNumber:
          type: string
          description: Reference to a physical artifact or other evidence collected during the course of an investigation
          minLength: 2
          maxLength: 128
        caseId:
          type: string
          description: Reference to the case UUID from the CourtCase entity
        application:
          type: string
          description: Application number with which this evidence is associated
        filingNumber:
          type: string
          description: Filing number with which this evidence is associated
        hearing:
          type: string
          description: Reference to the hearing where evidence could've been introduced.
        order:
          type: string
          description: Reference to the order that led to uploading this artifact
        mediaType:
          type: string
          description: Represents the type of artifact, such as audio, video, document, etc..
          example: AUDIO, VIDEO, DOC
        artifactType:
          type: string
          description: Represents the legal classification of the artifact, such as sworn statement, affidavit, testimony, etc.
          example: AFFIDAVIT, DEPOSITION, SWORN_STATEMENT, OTHER etc..
        filingType:
          type: string
          format: uuid
          example: master data values - caseFiling, application, direct
          description: master data for submission type as per the values mentioned in example. caseFiling to be used for all documents uploaded at the time of case e-filing. application is for submissions along with application and direct for documents directly uploaded. 
        sourceType:
          type: string
          description: Represents the legal classification of the source, such as COMPLAINANT, ACCUSED, COURT.
          example: COMPLAINANT, ACCUSED, COURT.
        sourceID:
          type: string
          description: The individual ID of the person who provided this artifact. In case of Person A providing an affidavit, this will be the individual ID of Person A.
        sourceName:
          type: string
          description: Users who may not be part of the system who've given evidence. SourceID or name is mandatory
          example: Mr. Peter, Assistant DGP
        applicableTo:
          type: array
          description: An array of individualIds of the litigants for whom this evidence has been provided. 
          items:
            type: string
        createdDate:
          type: integer
          format: int64
          description: Date this artifact was created. This may be different from the upload time which will be captured in the audit details.
        isActive:
          type: boolean
          description: Field to indicate soft delete of records. True if record is active, false if not.
          default: true
        isEvidence:
          type: boolean
          description: Field to indicate soft delete of records. True if record is evidence, false if not.
          default: false
        isVoid:
          type: boolean
          description: when a judge marks a document submission void. false by default
          default: false
        reason:
          type: string
          description: the reason for marking as void.
          minLength: 0
          maxLength: 256
        status:
          type: string
          description: The current status of the case as pulled from the Workflow service. Workflow service will hold the entire history of the case.
        file:
          $ref: >-
              https://raw.githubusercontent.com/egovernments/DIGIT-Specs/common-contract-update/Common%20Services/common-contract.yaml#/components/schemas/Document
        description:
          type: string
          description: Field that describes the artifact and its relevance to the case.
        artifactDetails:
          type: object
          description: Each evidence type may have specific fields depending on case type. 
        comments:
          type: array
          description: An array of comments representing the discussion between the parties of the case on this specific artifact.
          items:
            $ref: '#/components/schemas/Comment'
        additionalDetails:
          type: string
          description: >-
            This field is meant to hold any extra information that we want to
            store for a case.
        auditDetails:
          $ref: >-
            https://raw.githubusercontent.com/egovernments/DIGIT-Specs/common-contract-update/Common%20Services/common-contract.yaml#/components/schemas/AuditDetails
        workflow:
          $ref: >-
            https://raw.githubusercontent.com/egovernments/DIGIT-Specs/common-contract-update/Common%20Services/common-contract.yaml#/components/schemas/Workflow
    
    Comment:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: This id is autogenerated id of the artifact. It is the primary key
          readOnly: true
          minLength: 36
          maxLength: 36
        tenantId:
          type: string
          description: This is tenantId of the case based on the state.
        artifactId:
          type: string
          description: Refers to the artifact UUID that this is related to
        individualId:
          type: string
          description: The individual who is commenting on the artifact. In case lawyers do this on behalf of litigants, the individualId will be that of the litigant. The representative who's performing actions on behalf of will be captured in the audit details.
        comment:
          type: string
          description: Comments/responses from the user
          minLength: 2
          maxLength: 2048
        isActive:
          type: boolean
          description: Field to indicate soft delete of records
          default: true
        additionalDetails:
          type: string
          description: >-
            This field is meant to hold any extra information that we want to
            store for this entity.
        auditDetails:
          $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/common-contract-update/Common%20Services/common-contract.yaml#/components/schemas/AuditDetails'
      required: [tenantId, artifactId, individualId, comment]
   
    EvidenceRequest:
      type: object
      properties:
        RequestInfo:
          $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/common-contract-update/Common%20Services/common-contract.yaml#/components/schemas/RequestInfo'
        artifact:
          type: object
          items:
            $ref: '#/components/schemas/Artifact'
    EvidenceResponse:
      type: object
      properties:
        ResponseInfo:
          $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/common-contract-update/Common%20Services/common-contract.yaml#/components/schemas/ResponseInfo'
        artifact:
          type: object
          items:
            $ref: '#/components/schemas/Artifact'
        pagination:
          $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/common-contract-update/Common%20Services/common-contract.yaml#/components/schemas/Pagination'
    EvidenceSearchRequest:
      type: object
      properties:
        RequestInfo:
          $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/common-contract-update/Common%20Services/common-contract.yaml#/components/schemas/RequestInfo'
        tenantId:
          type: string
        criteria:
          $ref: '#/components/schemas/EvidenceSearchCriteria'
        pagination:
          $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/common-contract-update/Common%20Services/common-contract.yaml#/components/schemas/Pagination'
          
    EvidenceSearchResponse:
      type: object
      properties:
        ResponseInfo:
          $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/common-contract-update/Common%20Services/common-contract.yaml#/components/schemas/ResponseInfo'
        tenantId:
          type: string    
        artifacts:
          type: array
          description: his is an output field and will contain the list of artifacts found as per the search criteria
          items:
            $ref: '#/components/schemas/Artifact'
        pagination:
          $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/common-contract-update/Common%20Services/common-contract.yaml#/components/schemas/Pagination'
          
    EvidenceSearchCriteria:
      type: object
      description: the fields specified will be used in a logical AND condition
      properties:
        caseId:
          type: string
        applicationId:
          type: string
        owner:
          type: string
          format: uuid
          description: UUID of user
        filingNumber:
          type: string
        artifactType:
          type: string
        evidenceStatus:
          type: string  
        hearing:
          type: string
        order:
          type: string
        sourceId:
          type: string
          description: ID of the source (e.g., individual, organization) who provided the evidence
        sourceName:
          type: string
          description: Name of the source when formal ID is not available
        status:
          type: string
        artifactNumber:
          type: string

    EvidenceAddCommentRequest:
      type: object
      properties:
        RequestInfo:
          $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/common-contract-update/Common%20Services/common-contract.yaml#/components/schemas/RequestInfo'
        evidenceAddComment:
          $ref: '#/components/schemas/EvidenceAddComment'

    EvidenceAddCommentResponse:
      type: object
      properties:
        ResponseInfo:
          $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/common-contract-update/Common%20Services/common-contract.yaml#/components/schemas/ResponseInfo'
        evidenceAddComment:
          $ref: '#/components/schemas/EvidenceAddComment'

    EvidenceAddComment:
      type: object
      properties:
        tenantId:
          type: string
        comment:
          type: array
          description: An array of comments representing the discussion between the parties of the case on this specific artifact.
        artifactNumber:
          type: string