openapi: 3.0.1
info:
  title: Note API Documentation
  description: This draft API specification defines the Note registries.
  version: 1.0.0
tags:
  - name: Note
    description: APIs to create, update, search to a case note.
paths:
  /note/v1/create:
    post:
      tags:
        - Note
      summary: Create new note in the registry
      requestBody:
        description: Details for the new note + RequestInfo meta data.
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/NoteRequest'
        required: true
      responses:
        '201':
          description: RequestInfo with note details created successfully
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NoteResponse'
        '400':
          description: Note creation failed
          content:
            '*/*':
              schema:
                $ref: https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/ErrorRes
  /note/v1/update:
    post:
      tags:
        - Note
      summary: Update/edit a note
      description: API to update the note value.
      requestBody:
        description: Details for updating fields in the note + RequestInfo meta data.
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/NoteRequest'
        required: true
      responses:
        '200':
          description: ResponseInfo with note details updated successfully
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NoteResponse'
        '400':
          description: note updation failed
          content:
            '*/*':
              schema:
                $ref: https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/ErrorRes
  /note/v1/search:
    post:
      tags:
        - Note
      summary: Search for notes
      requestBody:
        description: Search criteria + RequestInfo meta data.
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/NoteSearchRequest'
        required: true
      responses:
        '200':
          description: ResponseInfo with note matching search criteria
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NoteListResponse'
        '400':
          description: Note search failed. Refer to response body for specifics.
          content:
            '*/*':
              schema:
                $ref: https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/ErrorRes
components:
  schemas:
    Note:
      description: Note registory
      required:
        - note
        - caseId
        - tenantId
        - submittedById
      type: object
      properties:
        id:
          type: string
          readOnly: true
        note:
          type: string
        caseId:
          type: string
        hearingId:
          type: string
        tenantId:
          type: string
          description: This is tenantId where the system is implemented.
          minLength: 2
          maxLength: 64
        createdDate:
          type: integer
          format: int64
        modifiedDate:
          type: integer
          format: int64
        submittedById:
          type: string
        workflow:
          $ref: https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/Workflow
        additionalDetails:
          type: object
          description: This field is meant to hold any extra information that we want to store for a note.
        auditDetails:
          $ref: https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/AuditDetails
    ConstituteElementRequest:
      type: object
      description: Constitute element request
      required:
        - constituentelementId
        - noteId
        - isCheked
      properties:
        constituentelementId:
          type: string
          description: This is id from constituent element master table id.
          minLength: 2
          maxLength: 64
        noteId:
          type: string
          description: This is noteId where the constitute element have checked/unchecked value to a note.
          minLength: 2
          maxLength: 64
        value:
          type: string
          description: This is constituent element string value
        isCheked:
          type: boolean
          description: checked/unchecked value for constitute element to a note 
    NoteRequest:
      type: object
      properties:
        RequestInfo:
          $ref: https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/RequestInfo
        note:
          $ref: '#/components/schemas/Note'
        constituentelement:
          type: array
          items:
            $ref: '#/components/schemas/ConstituteElementRequest'
    NoteResponse:
      type: object
      properties:
        ResponseInfo:
          $ref: https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/ResponseInfo
        notes:
          type: array
          items:
            $ref: '#/components/schemas/Note'
    NoteSearchRequest:
      type: object
      properties:
        RequestInfo:
          $ref: https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/RequestInfo
        criteria:
          $ref: '#/components/schemas/NoteCriteria'
        pagination:
          $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/common-contract-update/Common%20Services/common-contract.yaml#/components/schemas/Pagination'
    NoteListResponse:
      type: object
      properties:
        ResponseInfo:
          $ref: https://raw.githubusercontent.com/egovernments/DIGIT-OSS/master/core-services/docs/common-contract_v1-1.yml#/components/schemas/ResponseInfo
        list:
          type: array
          items:
            $ref: '#/components/schemas/Note'
        pagination:
          $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/common-contract-update/Common%20Services/common-contract.yaml#/components/schemas/Pagination'
    NoteCriteria:
      type: object
      properties:
        caseId:
          type: string
        noteId:
          type: string
        note:
          type: string
        defaultFields:
          type: boolean
        createdFromDate:
          type: integer
          format: int64
          description: search note within created date range. if only createdFromDate is specified, then notes for this filing date will be retrieved
        createdToDate:
          type: integer
          format: int64
