openapi: "3.0.0"

info:
  title: API specs for Order
  description:
    Order API paths and entity is defined in this file.
  version: "0.1.0"

servers:
  - url: ""

tags:
  - name: Order
    description: APIs for managing Orders related to a Case

paths:
  /order/v1/create:
    post:
      tags:
        - Order
      summary: create new order
      requestBody:
        description: Details for the new order + RequestInfo meta data.
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/OrderRequest'
        required: true
      responses:
        "201":
          description: ResponseInfo with order(s) updated successfully
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/OrderResponse'
        "400":
          description: order(s) creation failed
          content:
            '*/*':
              schema:
                $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/common-contract-update/Common%20Services/common-contract.yaml#/components/schemas/ErrorResponse'
      x-codegen-request-body-name: orderRequest

  /order/v1/update:
    post:
      tags:
        - Order
      summary: update hearing requests.
      requestBody:
        description: Details for the update order(s) + RequestInfo meta data.
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/OrderRequest'
        required: true
      responses:
        "201":
          description: ResponseInfo with order(s) updated successfully
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/OrderResponse'
        "400":
          description: order(s) update failed
          content:
            '*/*':
              schema:
                $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/common-contract-update/Common%20Services/common-contract.yaml#/components/schemas/ErrorResponse'
      x-codegen-request-body-name: orderRequest

  /order/v1/search:
    post:
      tags:
        - Order
      summary: search for orders
      description: |
        search order(s) based on different parameters
      parameters:
        - name: id
          in: query
          description: id of the order being searched
          schema:
            type: string
        - name: tenantId
          in: query
          description: tenantId whose order(s) are being searched
          schema:
            type: string
        - name: applicationNumber
          in: query
          description: the applicationNumber whose order(s) are being queried
          required: false
          schema:
            type: string
            format: uuid
        - name: filingNumber
          in: query
          description: the filingNumber of the case whose order(s) are being queried
          required: false
          schema:
            type: string
        - name: cnrNumber
          in: query
          description: the cnrNumber of the case whose order(s) are being queried
          required: false
          schema:
            type: string
        - name: status
          in: query
          description: the status of the order(s) being searched
          schema:
            type: string
      responses:
        "200":
          description: ResponseInfo with order list
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/OrderListResponse'
        "400":
          description: failed to find order(s)
          content:
            '*/*':
              schema:
                $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/common-contract-update/Common%20Services/common-contract.yaml#/components/schemas/ErrorResponse'

  /order/v1/exists:
    post:
      tags:
        - Order
      summary: order exits or not
      requestBody:
        description: check if the order(S) exists
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/OrderExistsRequest'
        required: true
      responses:
        "201":
          description: ResponseInfo with order(s) updated successfully
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/OrderExistsResponse'
        "400":
          description: failed to find Order
          content:
            '*/*':
              schema:
                $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/common-contract-update/Common%20Services/common-contract.yaml#/components/schemas/ErrorResponse'

components:
  schemas:
    OrderRequest:
      type: object
      properties:
        RequestInfo:
          $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/common-contract-update/Common%20Services/common-contract.yaml#/components/schemas/RequestInfo'
        order:
          $ref: '#/components/schemas/Order'
    OrderResponse:
      type: object
      properties:
        ResponseInfo:
          $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/common-contract-update/Common%20Services/common-contract.yaml#/components/schemas/ResponseInfo'
        order:
          $ref: '#/components/schemas/Order'

    OrderListResponse:
      type: object
      properties:
        ResponseInfo:
          $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/common-contract-update/Common%20Services/common-contract.yaml#/components/schemas/ResponseInfo'
        TotalCount:
          type: integer
        list:
          type: array
          items:
            $ref: '#/components/schemas/Order'

    OrderExistsRequest:
      type: object
      properties:
        RequestInfo:
          $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/common-contract-update/Common%20Services/common-contract.yaml#/components/schemas/RequestInfo'
        orderList:
          type: array
          items:
            $ref: '#/components/schemas/OrderExists'
    OrderExistsResponse:
      type: object
      properties:
        ResponseInfo:
          $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/common-contract-update/Common%20Services/common-contract.yaml#/components/schemas/ResponseInfo'
        orderList:
          type: array
          items:
            $ref: '#/components/schemas/OrderExists'

    OrderExists:
      type: object
      description: can send in any one of the values and Exists value will be populated with true or false. If multiple paramters are passed, then it will be a logical AND search
      properties:
        filingNumber:
          type: string
        cnrNumber:
          type: string
        applicationNumber:
          type: string
        orderNumber:
          type: string
        exists:
          type: boolean

    Order:
      description: An order is created as an outcome of an hearing or based on an application. Order will contain a set of tasks
      type: object
      required: [ tenantId, createdDate, orderType, status, isActive ]
      properties:
        id:
          type: string
          format: uuid
          minLength: 36
          maxLength: 36
          description: auto generated primary for internal reference
          readOnly: true
        tenantId:
          type: string
          description: This is tenantId of the case
        filingNumber:
          type: string
          description: the associated case
        cnrNumber:
          type: string
          description: The CNR number of the associated case. helps in faster search
        applicationNumber:
          type: array
          items:
            type: string
            description: application number the order is based on. Could be null if not based on any application
        hearingNumber:
          type: string
          description: in case the order is part of a hearing. if not, this will be set to null
        orderNumber:
          type: string
          minLength: 24
          maxLength: 256
          description: Order date and Case Name For example it will be Order number 1 for Rajpal et all vs State of Kerala
        linkedOrderNumber:
          type: string
          minLength: 24
          maxLength: 256
          description: Linked orderNumber for reissue of orders (for summons and warrants et)
        createdDate:
          type: string
          format: date
          description: the date on which the order was created. Can be treated as the start date also
        issuedBy:
          type: object
          properties:
            benchID:
              type: string
            judgeID:
              type: array
              items:
                type: string
                format: uuid
                minLength: 36
                maxLength: 36
            courtID:
              type: string
        orderType:
          type: string
          description: Master Data ID from OrderType master
        orderCategory:
          type: string
          description: Master data ID
          example: Intermediate, Judgement
        status:
          type: string
          description: workflow status
        comments:
          type: string
          description: any additional comments with regards the order, the judge may want to write
        isActive:
          type: boolean
          description: to handle soft delete
        statuteSection:
          $ref: './case-api-0.1.0.yaml#/components/schemas/StatuteSection'
        documents:
          type: array
          items:
            $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/common-contract-update/Common%20Services/common-contract.yaml#/components/schemas/Document'
        additionalDetails:
          type: string
          description: This field is meant to hold any extra information that we want to store.
        auditDetails:
          $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/common-contract-update/Common%20Services/common-contract.yaml#/components/schemas/AuditDetails'
        workflow:
          $ref: 'https://raw.githubusercontent.com/egovernments/DIGIT-Specs/common-contract-update/Common%20Services/common-contract.yaml#/components/schemas/Workflow'
