name: Advocate Workflow

on:
  push:
    # branches:
    #   - develop
    # paths:
    #   - 'backend/advocate/**'
  pull_request:
    # branches:
    #   - develop
    # paths:
    #   - 'backend/advocate/**'
  workflow_dispatch:

jobs:
  build-test-analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build and analyze with Maven and SonarCloud
        env:
          GITHUB_TOKEN: ${{ secrets.GHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
        run: |
          mvn -B -f backend/advocate/pom.xml verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
          -Dsonar.projectKey=pucar_advocate \
          -Dsonar.organization=pucar \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.qualitygate.wait=true

      - name: Run Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        env:
          JAVA_HOME: ${{ env.JAVA_HOME_17_X64 }}
        with:
          project: 'advocate'
          path: 'backend/advocate'
          format: 'HTML'
          args: --failOnCVSS 7 --enableRetired
          out: '${{ github.workspace }}/reports'

      - name: Upload Dependency-Check results
        uses: actions/upload-artifact@v3
        with:
          name: dependency-check-report
          path: ${{ github.workspace }}/reports
#      - name: Login to Azure Container Registry
#        if: github.ref == 'refs/heads/develop' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
#        run: docker login -u pucardev -p ${{ secrets.ACR_PASSWORD }} pucardev.azurecr.io
#
#      - name: Build and Push Docker image for advocate
#        if: github.ref == 'refs/heads/develop' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
#        run: |
#          docker build --build-arg WORK_DIR="backend/advocate" -t pucar_advocate:v1.0.0-${{ github.sha }} -f build/maven/Dockerfile .
#          docker tag pucar_advocate:v1.0.0-${{ github.sha }} pucardev.azurecr.io/pucar_advocate:v1.0.0-${{ github.sha }}
#          docker push pucardev.azurecr.io/pucar_advocate:v1.0.0-${{ github.sha }}
#
#      - name: Build and Push Docker image for advocate_DB
#        if: github.ref == 'refs/heads/develop' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
#        run: |
#          docker build -t pucar_advocate_db:v1.0.0-${{ github.sha }}  .
#          docker tag pucar_advocate_db:v1.0.0-${{ github.sha }} pucardev.azurecr.io/pucar_advocate_db:v1.0.0-${{ github.sha }}
#          docker push pucardev.azurecr.io/pucar_advocate_db:v1.0.0-${{ github.sha }}
#        working-directory: backend/advocate/src/main/resources/db
#      - name: Trigger Deployment Pipeline
#        if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
#        run: |
#          curl -X POST \
#          -H "Accept: application/vnd.github.v3+json" \
#          -H "Authorization: token ${{ secrets.GHUB_TOKEN }}" \
#          https://api.github.com/repos/pucardotorg/pucar-Devops/actions/workflows/dev.yaml/dispatches \
#          -d '{"ref":"Dev-0"}'
