name: Advocate Workflow

on:
  push:
    # branches:
    #   - develop
    # paths:
    #   - 'backend/advocate/**'
  pull_request:
    # branches:
    #   - develop
    # paths:
    #   - 'backend/advocate/**'
  workflow_dispatch:

jobs:
  depchecktest:
    runs-on: ubuntu-latest
    name: depecheck_test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build project with Maven
        run: mvn -B -f backend/advocate/pom.xml clean install
      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        with:
          project: 'advocate'
          path: 'backend/advocate'
          format: 'HTML'    
          others: ''
      - name: Upload Test results
        uses: actions/upload-artifact@master
        with:
           name: Depcheck report
           path: ${{github.workspace}}/reports
#      - name: Login to Azure Container Registry
#        if: github.ref == 'refs/heads/develop' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
#        run: docker login -u pucardev -p ${{ secrets.ACR_PASSWORD }} pucardev.azurecr.io
#
#      - name: Build and Push Docker image for advocate
#        if: github.ref == 'refs/heads/develop' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
#        run: |
#          docker build --build-arg WORK_DIR="backend/advocate" -t pucar_advocate:v1.0.0-${{ github.sha }} -f build/maven/Dockerfile .
#          docker tag pucar_advocate:v1.0.0-${{ github.sha }} pucardev.azurecr.io/pucar_advocate:v1.0.0-${{ github.sha }}
#          docker push pucardev.azurecr.io/pucar_advocate:v1.0.0-${{ github.sha }}
#
#      - name: Build and Push Docker image for advocate_DB
#        if: github.ref == 'refs/heads/develop' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
#        run: |
#          docker build -t pucar_advocate_db:v1.0.0-${{ github.sha }}  .
#          docker tag pucar_advocate_db:v1.0.0-${{ github.sha }} pucardev.azurecr.io/pucar_advocate_db:v1.0.0-${{ github.sha }}
#          docker push pucardev.azurecr.io/pucar_advocate_db:v1.0.0-${{ github.sha }}
#        working-directory: backend/advocate/src/main/resources/db
#      - name: Trigger Deployment Pipeline
#        if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
#        run: |
#          curl -X POST \
#          -H "Accept: application/vnd.github.v3+json" \
#          -H "Authorization: token ${{ secrets.GHUB_TOKEN }}" \
#          https://api.github.com/repos/pucardotorg/pucar-Devops/actions/workflows/dev.yaml/dispatches \
#          -d '{"ref":"Dev-0"}'
