name: analytics workflow
on:
  push:
    branches:
      - develop
    paths:
      - 'backend/analytics/**'
  pull_request:
    branches:
      - develop
    paths:
      - 'backend/analytics/**'
  workflow_dispatch:
jobs:
  docker_image-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Setup Docker
        uses: docker/setup-buildx-action@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Build and analyze analytics
        env:
          GITHUB_TOKEN: ${{ secrets.GHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
        run: mvn -B -f backend/analytics/pom.xml verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=pucar_analytics -Dsonar.organization=pucar -Dsonar.host.url=https://sonarcloud.io/ -Dsonar.qualitygate.wait=true

      - name: Login to Azure Container Registry
        if: github.ref == 'refs/heads/develop' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
        run: docker login -u pucardev -p ${{ secrets.ACR_PASSWORD }} pucardev.azurecr.io

      - name: Build and Push Docker image for analytics
        if: github.ref == 'refs/heads/develop' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
        run: |
          docker build --build-arg WORK_DIR="backend/analytics" -t pucar_analytics:v1.0.0-${{ github.sha }} -f build/maven/Dockerfile .
          docker tag pucar_analytics:v1.0.0-${{ github.sha }} pucardev.azurecr.io/pucar_analytics:v1.0.0-${{ github.sha }}
          docker push pucardev.azurecr.io/pucar_analytics:v1.0.0-${{ github.sha }}

      - name: trigger deployment pipeline
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.GHUB_TOKEN }}" \
          https://api.github.com/repos/pucardotorg/pucar-Devops/actions/workflows/dev.yaml/dispatches \
          -d '{"ref":"Dev-0"}'
