name: Advocate Image Build workflow
on:
  push:
    branches:
      - develop
      - hotfix/1.0
      - release/**
    tags:
      - 'v*'
    paths:
      - 'backend/advocate/**'
  pull_request:
    branches:
      - develop
      - hotfix/1.0
      - release/**
    paths:
      - 'backend/advocate/**'
  workflow_dispatch:
  workflow_call:
permissions:
  security-events: write
  contents: read

jobs:
  docker_image-build:
    if: (github.event_name == 'push' && (startsWith(github.ref, 'refs/heads/develop') || startsWith(github.ref, 'refs/heads/release/') || startsWith(github.ref, 'refs/heads/hotfix/') || startsWith(github.ref, 'refs/tags/v'))) || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Docker
        uses: docker/setup-buildx-action@v2

      - name: Dependency check
        uses: dependency-check/Dependency-Check_Action@main
        env:
          JAVA_HOME: /opt/jdk
        id: Depcheck
        with:
          project: 'advocate'
          path: 'backend/advocate'
          format: 'SARIF'
      - name: Upload SARIF result to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: reports/dependency-check-report.sarif
        if: always()

      # Login to Azure Container Registry
      - name: Login to Azure Container Registry
        run: docker login -u pucarsolutionsdev -p ${{ secrets.ACR_PASSWORD }} pucarsolutionsdev.azurecr.io

      - name: Set Version from Tag or Branch
        id: set_version
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}  # Use tag name for version
          elif [[ "${GITHUB_REF}" == refs/heads/* ]]; then
            # Use branch name as version, replacing '/' with '-'
            VERSION=${GITHUB_REF#refs/heads/}
            VERSION=$(echo "${VERSION}" | sed 's|/|-|g')
          else
            VERSION="latest"  # Default version if not a tag or branch
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Git commit_hash for service
        run: |
          commit_hash=$(git log -1 --pretty=format:%H -- backend/advocate)
          echo "commit_hash=$commit_hash" >> $GITHUB_ENV

      - name: Build and Push Docker image for Advocate
        run: |
          docker build --build-arg WORK_DIR="backend/advocate" -t pucarsolutionsdev.azurecr.io/pucar_advocate:${{ env.VERSION }}-${{ env.commit_hash }} -f build/maven/Dockerfile .
          docker push pucarsolutionsdev.azurecr.io/pucar_advocate:${{ env.VERSION }}-${{ env.commit_hash }}

      - name: Build and Push Docker image for Advocate_DB
        run: |
          docker build  -t pucarsolutionsdev.azurecr.io/pucar_advocate_db:${{ env.VERSION }}-${{ env.commit_hash }} -f  Dockerfile .
          docker push pucarsolutionsdev.azurecr.io/pucar_advocate_db:${{ env.VERSION }}-${{ env.commit_hash }}
        working-directory: backend/advocate/src/main/resources/db

  Workflow_Trigger:
    if: (github.event_name == 'push' && (startsWith(github.ref, 'refs/heads/develop') || startsWith(github.ref, 'refs/heads/release/') || startsWith(github.ref, 'refs/heads/hotfix/') || startsWith(github.ref, 'refs/tags/v'))) || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    needs: docker_image-build
    steps:
      - name: Set Workflow File Based on Branch
        id: set_workflow
        run: |
          if [ "${{ github.ref }}" == "refs/heads/develop" ]; then
            echo "WORKFLOW_FILE=solutions-dev.yaml" >> $GITHUB_ENV
          elif [ "${{ github.ref }}" == "refs/heads/release/0.4" ]; then
            echo "WORKFLOW_FILE=solutions-qa.yaml" >> $GITHUB_ENV
          elif [ "${{ github.ref }}" == "refs/heads/release/0.5" ]; then
            echo "WORKFLOW_FILE=solutions-dpg-dev.yaml" >> $GITHUB_ENV
          fi

      - name: Trigger Deployment Pipeline
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.GHUB_TOKEN }}" \
          https://api.github.com/repos/pucardotorg/pucar-Devops/actions/workflows/${{ env.WORKFLOW_FILE }}/dispatches \
          -d '{"ref":"Solutions-Pipeline"}'
