name: task workflow
on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'backend/task/**'
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'backend/task/**'
  workflow_dispatch:
jobs:
  docker_image-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Setup Docker
        uses: docker/setup-buildx-action@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Build and analyze task
        env:
          GITHUB_TOKEN: ${{ secrets.GHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
        run: mvn -B -f backend/task/pom.xml verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=pucar_task -Dsonar.organization=pucar -Dsonar.host.url=https://sonarcloud.io/ -Dsonar.qualitygate.wait=true

      - name: Login to Azure Container Registry
        if: (github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/main') && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
        run: docker login -u pucardev -p ${{ secrets.ACR_PASSWORD }} pucardev.azurecr.io

      - name: Build and Push Docker image for task
        if: (github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/main') && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
        run: |
          docker build --build-arg WORK_DIR="backend/task" -t pucar_task:v1.0.0-${{ github.sha }} -f build/maven/Dockerfile .
          docker tag pucar_task:v1.0.0-${{ github.sha }} pucardev.azurecr.io/pucar_task:v1.0.0-${{ github.sha }}
          docker push pucardev.azurecr.io/pucar_task:v1.0.0-${{ github.sha }}

      - name: Build and Push Docker image for task_DB
        if: (github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/main') && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
        run: |
          docker build -t pucar_task_db:v1.0.0-${{ github.sha }}  .
          docker tag pucar_task_db:v1.0.0-${{ github.sha }} pucardev.azurecr.io/pucar_task_db:v1.0.0-${{ github.sha }}
          docker push pucardev.azurecr.io/pucar_task_db:v1.0.0-${{ github.sha }}
        working-directory: backend/task/src/main/resources/db
