name: Code Scanning

on:
  push:

permissions:
  security-events: write
  contents: read

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Trivy
        uses: aquasecurity/trivy-action@v0.0.3
      - name: Run Trivy scan
        run: |
          trivy filesystem --format sarif -o trivy-results.sarif .
      - name: Upload SARIF results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results.sarif
